### ISSUE TITLE
[wish] more safety for the "safety critical" repo

### ISSUE THREAD

**Issue by dodikk** [stanislaw/awesome-safety-critical#12]
1) Store PDF articles as BLOBs inside a repo
This wish applies to the materials that do not represent some standard. Even if something happens to the hosting, your readers will still be able to read the corresponding papers. I am not sure about licensing issues, though.

For example, 
* The Power of Ten – Rules for Developing Safety Critical Code
* Military COTS-based systems: Not necessarily right off the shelf
* Mars Climate Orbiter Mishap Investigation
* etc.

2) A mirror on bitbucket and/or another hosting in order to not rely on "github" solely.

**Comment by stanislaw** [comment]
@dodikk thanks for raising this concern. All I can say is that I just didn't have time yet to think about it properly.

Licensing might be an issue indeed. So let's keep this issue open for a while until we have a good solution.

What mirroring schema would you suggest? Just pushing the thing to another remote once in a while?

**Comment by dodikk** [comment]
>> What mirroring schema would you suggest? Just pushing the thing to another remote once in a while?

I guess, this should work ok for now. 
And we'll have to add links to the mirrors to the `Readme` page once they are set up.

**Comment by nszceta** [comment]
Have you guys ever considered replication via IPFS?

**Comment by dodikk** [comment]
@nszceta , I'm ashamed to have not hearing about it until now https://ipfs.io
Looks interesting. Thanks.

**Comment by HairyFotr** [comment]
It's possible to add multiple push addresses to a single remote in your local git repo:
`git remote set-url --add --push origin "http://..."`

I also propose GitLab in addition to Bitbucket.

**Comment by stanislaw** [comment]
@HairyFotr thanks for the hint. 

I have made a [public mirror now on Gitlab](https://gitlab.com/stanislaw/awesome-safety-critical-mirror) and a private one on Bitbucket.

P.S. @dodikk I think I understand now have a good approach for local pdfs in mind. I will get to it very soon.

**Comment by stanislaw** [comment]
@dodikk I thought more about this and decided to not implement the complete backup strategy for now.

However I have added the most interesting pdfs to the [Backup folder](https://github.com/stanislaw/awesome-safety-critical/tree/5ccc8f85d056539269c498fdac5b968d0e577b17/Backup). 

For the rest of the materials let the [Wayback Machine](https://archive.org/web/) to be our last resort.

**Comment by dodikk** [comment]
>> @dodikk I thought more about this and decided to not implement the complete backup strategy for now.

That's completely up to you. 
It's cool to see your repo getting the mirrors and the link checking (`awesome-bot`) CI step.
