### ISSUE TITLE
Add John W. McCormick Ada books

### ISSUE THREAD

**Issue by jviotti** [stanislaw/awesome-safety-critical#27]
I think this list should mention some of John W. McCormick's books, directly related to safety critical software:

- [Building High Integrity Applications with SPARK](https://www.amazon.com/Building-High-Integrity-Applications-SPARK/dp/1107656842/ref=sr_1_1?s=books&ie=UTF8&qid=1489271661&sr=1-1&keywords=high+integrity+spark)
- [Building Parallel, Embedded, and Real-Time Applications with Ada](https://www.amazon.com/Building-Parallel-Embedded-Real-Time-Applications/dp/0521197163/ref=sr_1_1?s=books&ie=UTF8&qid=1489271672&sr=1-1&keywords=embedded+ada)

**Comment by stanislaw** [comment]
Thanks @jviotti ! Closed via #28.
